// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protobuf.proto

/*
Package calculator is a generated protocol buffer package.

It is generated from these files:
	proto/protobuf.proto

It has these top-level messages:
	SumRequest
	SumResponse
*/
package calculator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SumRequest struct {
	FNum int32 `protobuf:"varint,1,opt,name=f_num,json=fNum" json:"f_num,omitempty"`
	SNum int32 `protobuf:"varint,2,opt,name=s_num,json=sNum" json:"s_num,omitempty"`
}

func (m *SumRequest) Reset()                    { *m = SumRequest{} }
func (m *SumRequest) String() string            { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()               {}
func (*SumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SumRequest) GetFNum() int32 {
	if m != nil {
		return m.FNum
	}
	return 0
}

func (m *SumRequest) GetSNum() int32 {
	if m != nil {
		return m.SNum
	}
	return 0
}

type SumResponse struct {
	SumRes int32 `protobuf:"varint,1,opt,name=sum_res,json=sumRes" json:"sum_res,omitempty"`
}

func (m *SumResponse) Reset()                    { *m = SumResponse{} }
func (m *SumResponse) String() string            { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()               {}
func (*SumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SumResponse) GetSumRes() int32 {
	if m != nil {
		return m.SumRes
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CalculatorService service

type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := grpc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CalculatorService service

type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/protobuf.proto",
}

func init() { proto.RegisterFile("proto/protobuf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x07, 0x93, 0x49, 0xa5, 0x69, 0x7a, 0x60, 0x86, 0x10, 0x57, 0x72, 0x62, 0x4e, 0x72,
	0x69, 0x4e, 0x62, 0x49, 0x7e, 0x91, 0x92, 0x19, 0x17, 0x57, 0x70, 0x69, 0x6e, 0x50, 0x6a, 0x61,
	0x69, 0x6a, 0x71, 0x89, 0x90, 0x30, 0x17, 0x6b, 0x5a, 0x7c, 0x5e, 0x69, 0xae, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x6b, 0x10, 0x4b, 0x9a, 0x5f, 0x69, 0x2e, 0x48, 0xb0, 0x18, 0x2c, 0xc8, 0x04, 0x11,
	0x2c, 0xf6, 0x2b, 0xcd, 0x55, 0x52, 0xe3, 0xe2, 0x06, 0xeb, 0x2b, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x15, 0x12, 0xe7, 0x62, 0x2f, 0x2e, 0xcd, 0x8d, 0x2f, 0x4a, 0x2d, 0x86, 0x6a, 0x65, 0x2b, 0x06,
	0xcb, 0x1a, 0xf9, 0x72, 0x09, 0x3a, 0xc3, 0x6d, 0x0b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15,
	0xb2, 0xe0, 0x62, 0x0e, 0x2e, 0xcd, 0x15, 0x12, 0xd3, 0x43, 0x38, 0x44, 0x0f, 0xe1, 0x0a, 0x29,
	0x71, 0x0c, 0x71, 0x88, 0x2d, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x1f, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x19, 0x0f, 0x3b, 0x9a, 0xd9, 0x00, 0x00, 0x00,
}
